
# dataset info
dataset_name: "EUVP"
dataset_path: "/home/ashwin/Project/DATASETS/Bx_Data/Paired/"

# image info
chans: 3
im_width: 1920
im_height: 1088

# other params
val_interval: 1000 # steps
ckpt_interval: 1  # epochs




